apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: "Mutating webhook demo pod"
    openshift.io/display-name: ""
  name: sgc-mutating-demo-app
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  namespace: sgc-mutating-demo-app
  labels:
    webhook.toleration-mutate: enabled
spec:
  containers:
  - name: nginx
    image: nginx