apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-webhook
  namespace: sgc-mutating-webhook
  labels:
    app: mutating-webhook
spec:
  replicas: 1
    spec:
      containers:
        - name: example-webhook
          image: sgchub/kubernetes-webhook:main-b3fe6df
          imagePullPolicy: Always
