apiVersion: v1
kind: Service
metadata:
  name: example-webhook-service
  namespace: default
spec:
  selector:
    app: example-webhook
  ports:
    - port: 8443
      name: application
    - port: 8080
      name: metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-webhook
  namespace: default
  labels:
    app: example-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-webhook
  template:
    metadata:
      labels:
        app: example-webhook
    spec:
      containers:
        - name: example-webhook
          image: sgchub/kubernetes-webhook:main-91b0acd
          imagePullPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-webhook-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/q/metrics"
            backend:
              service:
                name: example-webhook-service
                port:
                  number: 8080
          - pathType: Prefix
            path: "/webhook/mutate"
            backend:
              service:
                name: example-webhook-service
                port:
                  number: 8443
---
