apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: example-webhook
webhooks:
  - name: example-webhook.default.svc.cluster.local
    admissionReviewVersions:
      - "v1beta1"
    sideEffects: "None"
    timeoutSeconds: 30
    objectSelector:
      matchLabels:
        example-webhook-enabled: "true"
    clientConfig:
      service:
        name: example-webhook
        namespace: default
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURiRENDQWxTZ0F3SUJBZ0lVQ1FvQU9tOS9BM1VmZGx1d3hYZlpjOE5zTDdFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1RqRUxNQWtHQTFVRUJoTUNSRXN4RURBT0JnTlZCQWdUQjBWNFlXMXdiR1V4RGpBTUJnTlZCQWNUQlVoRgpTa3hUTVJBd0RnWURWUVFLRXdkRmVHRnRjR3hsTVFzd0NRWURWUVFMRXdKRFFUQWVGdzB5TWpBeU1UTXhNalExCk1EQmFGdzB5TnpBeU1USXhNalExTURCYU1FNHhDekFKQmdOVkJBWVRBa1JMTVJBd0RnWURWUVFJRXdkRmVHRnQKY0d4bE1RNHdEQVlEVlFRSEV3VklSVXBNVXpFUU1BNEdBMVVFQ2hNSFJYaGhiWEJzWlRFTE1Ba0dBMVVFQ3hNQwpRMEV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ2pSZjluZHVSTzdpM1laTjZ6CkFyVjd0VE1qcmh1c2ZoYVhzN2RjenovREZYR3lpa0grakpFUGp6Y3RsdnRnYnVXNDJ0aGM0VVFyWlUrb1IwSlEKUUVTbmhGcjRjNU1oMEJQNXNDVWJXNVdodFZnazQ4K3VQTlBrS1BXaXlzOG1Wc1owTTdPaGdaVGltYWtWc0RZOQoyUDJ6OFFheHdwSS9pLzN5aGJ0bTdMeEZwTXN6RnJaOTRwcEJjSW0yNSsvcGdGRThuSGJFNmhXYUNsZ0lJenZHCjBQclk4WGcrQ2ZrTXVzNFM1L1UvdU01alhwa2RXdFFTdS8zcHRMcE1JUEswMEZXYTFVb1JwWjQ5NVA3cDF3RnMKUHoyUUpQWXhZSFFpT05BdmgrL2xpQlFrcm1VRitMaG5KYUFZdmExVHhSczhuZ3E5QnJBSjZCb2k0SkZEK0pmYgpyTDFKQWdNQkFBR2pRakJBTUE0R0ExVWREd0VCL3dRRUF3SUJCakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHCkExVWREZ1FXQkJUR1lNajVia0JiYjFvK3JRVFlmdGxGT1BzTGlUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUEKVFQweWlEVmJXTHFmZnRqQlpxVGJvQ29wdUpuc2RLVUFTSjRwVVh3L0pDMjhXMXlST21WVlA5ZEd5Q3dXMTd0VAozcTFvUXBqaTNIOG1uWCtyZk14d1ZhcWxvMkpZNm4wTEFyV2N1bS9GenJ6dUpsUlJ0VFp4MkZRY0o4MjhtWDV4CmttZmo3RTRTQzZqUDQ0bmswUFFPREEreVczbU1MTW04REFIaElzcXVIaEVuWm02YUdwbkt1S0xibWwwNXdxaFMKSE1sc0FaUUcyRWxBRWNQWUV1UEQ3N3B2TmcyV25oVVNpbXpXY0FLeEhhMUhwZHM1UGRCZ1Iwc1lMVkhvczRiZApBVUd1UTRSczdGK01SOSt5L01oZFFnMzRwdC9YZWpGcmpHTklCdVNSaVN2c1ljK2xCQlpnUHBPazNaQmNCb09RCmRNN05rdkw4eGRNbWdFUW5vaGYrNHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]